version: '3'

services:
  php:
    build:
      context: ./docker/php
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
